function outputImagesFromDataCubeScript(h5name, outputDirectory)
%% This Code takes a datacube and outputs quantised images for all days and
%% modalities in the outputDirectory.
%% It is a wrapper for the Matlab function outputImagesFromDataCube
%
% USAGE:
%   outputImagesFromDataCubeScript('/home/cosc/csprh/linux/HABCODE/scratch/HAB/tmpTest/testCubes/Cube_09073_09081_737173.h5', '/home/cosc/csprh/linux/HABCODE/scratch/HAB/tmpTest/CNNIms');
% INPUT:
%   h5name: Name of the input datacube
%   outputDirectory: place to put the quantised images
% OUTPUT:
%   -
% THE UNIVERSITY OF BRISTOL: HAB PROJECT
% Author Dr Paul Hill March 2019

addpath('../extractData/postProcess');
addpath('../extractData');
[~, tmpStruct] = getHABConfig;

resolution = str2num(tmpStruct.confgData.resolution.Text);
distance1 = str2num(tmpStruct.confgData.distance1.Text);
numberOfDays = str2num(tmpStruct.confgData.numberOfDaysInPast.Text);
outputRes = str2num(tmpStruct.confgData.outputRes.Text);
alphaSize = str2num(tmpStruct.confgData.alphaSize.Text);

inputRangeX = [0 distance1/resolution];
inputRangeY = [0 distance1/resolution];

%minima and maxima of the groups is needed to scale the output images.
%groupMaxAndMin is generated by cubeSequence.m
load groupMaxAndMin

outputImagesFromDataCube(outputDirectory, numberOfDays, groupMinMax, inputRangeX, inputRangeY, alphaSize, outputRes, h5name);
quit;

%needs to quit as called by HABDetectScript


